from ase.io.trajectory import Trajectory


def traj2dump(traj_file: str = "opt.traj", dump_file: str = "opt.dump"):
    # 读取轨迹文件
    traj = Trajectory(traj_file)

    # 收集所有元素类型并生成映射
    elements = set()
    for atoms in traj:
        elements.update(atoms.get_chemical_symbols())
    element_to_type = {elem: i + 1 for i, elem in enumerate(sorted(elements))}

    # 写入 LAMMPS dump 文件
    with open(dump_file, 'w') as f:
        for step, atoms in enumerate(traj):
            f.write(f"ITEM: TIMESTEP\n{step}\n")
            f.write(f"ITEM: NUMBER OF ATOMS\n{len(atoms)}\n")

            # 处理盒子
            cell = atoms.cell
            if cell.orthorhombic:
                f.write("ITEM: BOX BOUNDS pp pp pp\n")
                for i in range(3):
                    f.write(f"0.0 {cell.lengths()[i]:.6f}\n")
            else:
                xy, xz, yz = cell[1][0], cell[2][0], cell[2][1]
                f.write("ITEM: BOX BOUNDS xy xz yz pp pp pp\n")
                f.write(f"0.0 {cell[0][0]:.6f} {xy:.6f}\n")
                f.write(f"0.0 {cell[1][1]:.6f} {xz:.6f}\n")
                f.write(f"0.0 {cell[2][2]:.6f} {yz:.6f}\n")

            # 写入原子信息
            f.write("ITEM: ATOMS id type x y z\n")
            for i, atom in enumerate(atoms):
                elem = atom.symbol
                atom_type = element_to_type[elem]
                x, y, z = atom.position
                f.write(f"{i + 1} {atom_type} {x:.6f} {y:.6f} {z:.6f}\n")


def traj2xdatcar(traj_file: str = "opt.traj"):
    # 读取轨迹文件
    traj = Trajectory(traj_file)
    first_frame = traj[0]

    # 提取初始信息
    initial_cell = first_frame.get_cell()
    chemical_symbols = first_frame.get_chemical_symbols()
    elements = []
    counts = []
    seen_symbols = set()

    # 按首次出现顺序整理元素和数量
    for symbol in chemical_symbols:
        if symbol not in seen_symbols:
            elements.append(symbol)
            seen_symbols.add(symbol)
            counts.append(1)
        else:
            counts[-1] += 1

    # 写入XDATCAR头部
    with open('XDATCAR', 'w') as f:
        f.write("Generated by ASE\n1.0\n")
        for vec in initial_cell:
            f.write(f"{vec[0]:.10f} {vec[1]:.10f} {vec[2]:.10f}\n")
        f.write(" ".join(elements) + "\n")
        f.write(" ".join(map(str, counts)) + "\n")

    # 逐帧写入坐标
    with open('XDATCAR', 'a') as f:
        for step, atoms in enumerate(traj, 1):
            current_symbols = atoms.get_chemical_symbols()
            if current_symbols != chemical_symbols:
                raise ValueError(f"元素在帧 {step} 不一致！")

            scaled_pos = atoms.get_scaled_positions(wrap=False)
            f.write(f"Direct configuration= {step}\n")
            for x, y, z in scaled_pos:
                f.write(f"{x:.10f} {y:.10f} {z:.10f}\n")
